.pc
.TH "ME TV" 1 "2009-07-09" "0.9.6" "Me TV Manual"

.SH NAME
me-tv \- a digital television (DVB) viewer for GNOME

.SH SYNOPSIS
.B me-tv
.I [-?|--help]
.I [-v|--verbose]
.I [-s|--safe-mode]
.I [-m|--minimised]
.I [-d|--default-device]
.I [--disable-epg]
.I [--disable-epg-thread]
.I [--read-timeout]
.I [--display=DISPLAY]

.SH DESCRIPTION
Me TV is a GNOME desktop application for watching digital television services 
that use the DVB standard.  Me TV works with DVB-T/C/S and ATSC cards that have 
kernel driver support.

Me TV uses the xine video player to render its output onto its video window. 
Me TV reads the Electronic Program Guide (EPG) data that is transmitted over 
the air to populate a built-in program guide which can be used for scheduling 
recordings.

Me TV has a built-in scanner which requires an initial scan file.

.SH OPTIONS
.TP
.B -?|--help
Show help options.
.TP
.B -v|--verbose
Show verbose output.
.TP
.B -s|--safe-mode
Show the preferences dialog an don't show video upon start.
.TP
.B -m|--minimised-mode
Show minimised in notification area at startup.
.TP
.B -d|--default-device
Set the default DVB frontend device (e.g. /dev/dvb/adapter0/frontend0)
.TP
.B --disable-epg
Stops the rendering of the EPG event buttons on the UI.
.TP
.B --disable-epg-thread
Disable the EPG thread.  Me TV will stop collecting EPG events.
.TP
.B --read-timeout
How long to wait (in seconds) before timing out while waiting for data from demuxer (default 5)
.TP
.B --display=DISPLAY
X display to use

.SH AUTHOR
Michael Lamothe (2007-2009) <michael.lamothe@gmail.com>.

.SH COPYRIGHT
Copyright (C) 2009 Michael Lamothe <michael.lamothe@gmail.com>.
