# -*- mode:python; coding:utf-8; -*-

#  Me TV — A DVB player.
#
#  Copyright © 2014 Russel Winder
#
#  This program is free software: you can redistribute it and/or modify it under the terms of the GNU
#  General Public License as published by the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even
#  the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public
#  License for more details.
#
#  You should have received a copy of the GNU General Public License along with this program.  If not, see
#  <http://www.gnu.org/licenses/>.
#
#  Author : Russel Winder <russel@winder.org.uk>

Import('environment', 'main_environment', 'xine_player_environment')

test_main_environment = main_environment.Clone()
test_main_environment.Append(CPPPATH=[
    test_main_environment['catch_directory'],
    '#src',
    '#{}/src'.format(test_main_environment['build_directory'])]
)

test_executables = [test_main_environment.Program(x) for x in Glob('*.cc')]

Return('test_executables')
