# -*- mode:python; coding:utf-8; -*-

#  Me TV — A DVB-T player.
#
#  Copyright © 2014 Russel Winder
#
#  This program is free software: you can redistribute it and/or modify it under the terms of the GNU
#  General Public License as published by the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even
#  the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public
#  License for more details.
#
#  You should have received a copy of the GNU General Public License along with this program.  If not, see
#  <http://www.gnu.org/licenses/>.
#
#  Author : Russel Winder <russel@winder.org.uk>

Import('environment')

po_extension = '.po'
compiled_extension = '.mo'

built_po_files = []

for po_file in Glob('*' + po_extension):
    country_code = po_file.name[:-len(po_extension)]
    built = environment.Command(country_code + compiled_extension, po_file, "msgfmt -o $TARGET $SOURCES")
    environment.Alias('install', environment.InstallAs(environment['PACKAGE_LOCALE_DIR'] + '/' + country_code + '/LC_MESSAGES/me-tv.mo', built))
    built_po_files.append(built)

#env = Environment(tools = ["default", "gettext"])
#env.MOFiles(LINGUAS_FILE=1)

#env['XGETTEXTPATH'] = ['../']
#env.Translate(LINGUAS_FILE=1, XGETTEXTFROM='POTFILES.in')

Return('built_po_files')
